REPO = 'c:/users/rodi/Github/kingair-Sys26-test';
FILES = dir(fullfile(REPO,'**/*.*'));
NAMES = {FILES.name};
FOLDERS = {FILES.folder};
dNAMES = fullfile(FOLDERS,NAMES);
pNAME = 'xlsfiles';

GETS = { ...
    'shakedown26' ...
    'radfire16' ...
    'flux20' ...
    'chacha22' ...
    'cheesehead19' ...
    'copemed13' ...
    'dilbert20' ...
    'dilbert21' ...
    'snowie17' ...
    'trans2am21' ...
    'trans2am22' ...
    'searmar17' ...
    'pecan15' ...
    }

PROJ0 = fullfile(REPO,'bbflux18');
PROJ1 = fullfile(PROJ0,'xlsfiles');
for ii=1:numel(GETS)
    PROJ = fullfile(REPO,GETS{ii})
    cd(PROJ)
    cleanup
    blurf=true;
    if(blurf)
        delete(fullfile("xlsfiles","*.*"))
        delete('xlsfiles')
        copyfile(PROJ1,fullfile(PROJ,'xlsfiles'));
        delete('global_atts.txt')
        copyfile(fullfile(PROJ0,'global_atts.txt'),PROJ)
        copyfile(fullfile(PROJ0,'do_batch26.m'),PROJ)
    end
    cd(fullfile(PROJ,'xlsfiles'))
    make_database('variablesXX-1.txt');
    cd ../..
end

