function dpr_alpha = dpr_alpha(fq,ta,tb)
%DPR_ALPHA
%    DPR_ALPHA = DPR_ALPHA(FQ,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 17:36:36

t2 = ta.^2;
dpr_alpha = -(-fq+fq.*t2+fq.*ta.*2.0)./(t2.*2.0+tb.^2.*2.0+2.0);
end

