function dprax = dpra_simX(f,q,ta,tb)
%DPRA_SIM
%    DPRAX = DPRA_SIMX(F,Q,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Nov-2025 07:27:04

t2 = ta.^2;
dprax = -(-f.*q+f.*q.*t2+f.*q.*ta.*2.0)./(t2.*2.0+tb.^2.*2.0+2.0);
end
