function dpraX = dpra_simX_sim(fq,ta,tb)
%dpra_simX_sim
%    dpraX = dpra_simX_sim(FQ,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 07:55:34

t2 = ta.^2;
dpraX = -(-fq+fq.*t2+fq.*ta.*2.0)./(t2.*2.0+tb.^2.*2.0+2.0);
end
