function dprax = dpra_sim(fq,ta,tb)
%DPRA_SIM
%    DPRAX = DPRA_SIM(FQ,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Feb-2026 06:43:48

t2 = ta.^2;
dprax = -(-fq+fq.*t2+fq.*ta.*2.0)./(t2.*2.0+tb.^2.*2.0+2.0);
end
