function out1 = fq_sim(dpa,dpb,dpr)
%FQ_SIM
%    OUT1 = FQ_SIM(DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 07:55:34

t2 = dpr.*2.0;
t3 = dpb.^2;
out1 = dpb+t2-((t3.*2.0+dpa.^2).*(dpb+t2-sqrt(2.0).*sqrt(t3+dpb.*t2+dpr.*t2)))./(t3.*2.0);
end
