function out1 = q_sim(dp1a,dpa,dpb,dpr)
%Q_SIM
%    OUT1 = Q_SIM(DP1A,DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 07:55:34

t2 = dpb.^2;
out1 = dp1a-((t2+dpa.^2).*(dpb+dpr.*2.0-sqrt(2.0).*sqrt(t2+dpb.*dpr.*2.0+dpr.^2.*2.0)))./(t2.*2.0);
end
