function out1 = ta_beta(dpa,dpb,dpr)
%TA_BETA
%    OUT1 = TA_BETA(DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-May-2026 09:24:44

t2 = dpr.*2.0;
out1 = -dpa.*1.0./dpb.^2.*(dpb+t2-sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2));
end
