function out1 = ta_new_sim(dpa,dpb,dpra)
%TA_NEW_SIM
%    OUT1 = TA_NEW_SIM(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Feb-2026 06:43:48

t2 = dpa.*dpb;
out1 = -(t2+dpb.*dpra.*2.0-sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0))./t2;
end
