function out1 = ta_simX(dpa,dpb,dpra)
%ta_simX
%    OUT1 = ta_simX(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 07:55:34

t2 = dpa.*dpb;
out1 = -(t2+dpb.*dpra.*2.0-sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0))./t2;
end
