function out1 = ta_sim(dpa,dpb,dpr)
%TA_SIM
%    OUT1 = TA_SIM(DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 07:55:34

t2 = dpr.*2.0;
out1 = -dpa.*1.0./dpb.^2.*(dpb+t2-sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2));
end
