function out1 = tb_alpha1(dpa,dpb,dpra)
%TB_ALPHA1
%    OUT1 = TB_ALPHA1(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 16:27:31

out1 = -1.0./dpa.^2.*(dpa.*dpb+dpb.*dpra.*2.0-sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0));
end
