function out1 = tb_alpha(dpa,dpb,dpra)
%TB_ALPHA
%    OUT1 = TB_ALPHA(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-May-2026 09:24:45

out1 = -1.0./dpa.^2.*(dpa.*dpb+dpb.*dpra.*2.0-sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0));
end
