function out1 = tb_new_sim(dpa,dpb,dpra)
%TB_NEW_SIM
%    OUT1 = TB_NEW_SIM(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Feb-2026 06:43:48

out1 = -1.0./dpa.^2.*(dpa.*dpb+dpb.*dpra.*2.0-sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0));
end
