function out1 = tb_sim(dpb,dpr)
%TB_SIM
%    OUT1 = TB_SIM(DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 07:55:34

t2 = dpr.*2.0;
out1 = -(dpb+t2-sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2))./dpb;
end
