function dpr_alpha = DPN_alpha(fq,ta,tb)
%DPN_alpha
%    DPR_ALPHA = DPN_alpha(FQ,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-May-2026 09:34:00

t2 = ta.^2;
dpr_alpha = -(-fq+fq.*t2+fq.*ta.*2.0)./(t2.*2.0+tb.^2.*2.0+2.0);
end
