function out1 = f_beta(dp1a,dpa,dpb,dpr)
%F_BETA
%    OUT1 = F_BETA(DP1A,DPA,DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    02-Apr-2026 07:40:10

t2 = dpr.*2.0;
t3 = dpa.^2;
t5 = dpb.^2;
t6 = dpb.^3;
t8 = dpr.^2;
t11 = sqrt(2.0);
t4 = t3.^2;
t7 = t5.^2;
t9 = dpb.*t2;
t10 = dpr.*t2;
t12 = dp1a.*t6.*4.0;
t13 = dp1a.*dpr.*t5.*8.0;
t14 = t5+t9+t10;
t15 = sqrt(t14);
t16 = t11.*t15;
t17 = -t16;
t18 = dpb+t2+t17;
out1 = (t4+t7.*6.0-t12-t13+dpr.*t6.*1.6e+1+t3.*t5.*7.0+t3.*t8.*1.6e+1+t5.*t8.*1.6e+1-t6.*t18.*2.0+dpb.*dpr.*t3.*1.6e+1+dp1a.*t3.*t18.*2.0+dp1a.*t5.*t18.*4.0-dpb.*t3.*t18.*2.0-dpr.*t3.*t18.*4.0-dpr.*t5.*t18.*4.0)./(t4+t7+t12+t13+t3.*t5.*2.0-dp1a.^2.*t5.*4.0+dp1a.*dpb.*t3.*4.0+dp1a.*dpr.*t3.*8.0);
end
