function out1 = tb_beta(dpb,dpr)
%TB_BETA
%    OUT1 = TB_BETA(DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    20-May-2026 09:33:59

t2 = dpr.*2.0;
out1 = -(dpb+t2-sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2))./dpb;
end
