function [y]=decimateByFactors(varargin);
%function [y]=decimateByFactors(x,R,type,FillValue);
%DEZIMATE: decimate by factors
%function [y]=dezimate(x,n,a);
%$Source: /home/cvs/kingair/Sys09/dezimate.m,v $
%Project $Name: trans2am21_qc0 $ ($Revision: 1.2 $)
%$Date: 2012/02/20 13:53:13 $

narginchk(2,4); % no defaults

x=varargin{1}; % input data
R=varargin{2}; % decimation factor
N=varargin{3}; % Always FIR
N='FIR';
if(nargin>4)
    FillValue=varargin{4};
else
    FillValue=-32768;
end

%    Y = DECIMATE(X,R,N) uses an N'th order Chebyshev filter.  For N greater
%    than 13, DECIMATE will produce a warning regarding the unreliability of
%    the results.  See NOTE below.
%
%    Y = DECIMATE(X,R,['FIR']) uses a 30th order FIR filter generated by
%    FIR1(30,1/R) to filter the data.

x0=x; %save
nn=length(x);
ii=1:nn; %indices of all

%Problem. In the decimate.m function:
%Note: For large R, the Chebyshev filter design might be incorrect
%    due to numeric precision limitations.  In this case, DECIMATE will
%    use a lower filter order.  For better anti-aliasing performance, try 
%    breaking R up into its factors and calling DECIMATE several times.

if(R==1000),
    y=decimate1(decimate1(decimate1(x,10,N),10,N),10,N);
elseif(R==500),
    y=decimate1(decimate1(x,25,N),20,N);
elseif(R==200),
    y=decimate1(decimate1(x,20,N),10,N);
elseif(R==100),
    y=decimate1(decimate1(x,10,N),10,N);
else
    y=decimate1(x,R,N);
end

