# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28;C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits2-build")
set(CPACK_CMAKE_GENERATOR "MinGW Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "AMD64")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "expat, libexpat-dev")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/mingw64/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "udunits built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ;ZIP")
set(CPACK_IGNORE_FILES "/\\.;~\$;\\.t2p/;\\.o\$;\\.lo\$;\\.la\$;\\.libs/;/test/;/autom4te\\.cache/;/build/;/conda\\.recipe/;/consistent\$;/udunits2\$;\\.log\$;/appveyor\\.yml\$;/BACKLOG\$;/build\\.gradle\$;/check.*\$;/commit\$;/config\\.status\$;/dev-makefile\$;/Makefile\$;/publish\$;/push\$;/scan\$;/stamp-h1\$;/t.t\$;\\.gz\$;\\.rpm\$;/yum-upload\$")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28/..")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME ".. UDUNITS-2")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_HELP_LINK "http://www.unidata.ucar.edu/software/udunits")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME ".. UDUNITS-2")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "http://www.unidata.ucar.edu/software/udunits")
set(CPACK_OBJCOPY_EXECUTABLE "C:/ProgramData/MATLAB/SupportPackages/R2025b/3P.instrset/mingw_w64.instrset/bin/objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "C:/ProgramData/MATLAB/SupportPackages/R2025b/3P.instrset/mingw_w64.instrset/bin/objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits2-build/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "support-udunits@unidata.ucar.edu")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28/README")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C library and utility for units of physical quantities")
set(CPACK_PACKAGE_EXECUTABLES "udunits2")
set(CPACK_PACKAGE_FILE_NAME "udunits-2.2.28")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.unidata.ucar.edu/software/udunits")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "..")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "..")
set(CPACK_PACKAGE_NAME "udunits")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "University Corporation for Atmospheric Research")
set(CPACK_PACKAGE_VERSION "2.2.28")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "2")
set(CPACK_PACKAGE_VERSION_PATCH "28")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")
set(CPACK_READELF_EXECUTABLE "C:/ProgramData/MATLAB/SupportPackages/R2025b/3P.instrset/mingw_w64.instrset/bin/readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28/COPYRIGHT")
set(CPACK_RESOURCE_FILE_README "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28/README")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/mingw64/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_PROVIDES "udunits2(1), libudunits2, udunits2.h, converter.h")
set(CPACK_RPM_PACKAGE_REQUIRES "expat, expat-devel")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/\\.;~\$;\\.t2p/;\\.o\$;\\.lo\$;\\.la\$;\\.libs/;/test/;/autom4te\\.cache/;/build/;/conda\\.recipe/;/consistent\$;/udunits2\$;\\.log\$;/appveyor\\.yml\$;/BACKLOG\$;/build\\.gradle\$;/check.*\$;/commit\$;/config\\.status\$;/dev-makefile\$;/Makefile\$;/publish\$;/push\$;/scan\$;/stamp-h1\$;/t.t\$;\\.gz\$;\\.rpm\$;/yum-upload\$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits-2.2.28;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits2-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "udunits-2.2.28")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_VERBATIM_VARIABLES "YES")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/rodi/Github/kingair-Sys26/Sys26/config/udunits-windows/udunits2-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
