clear mex_udunits2   % to unload it
delete mex_udunits2.mexw64;
mex -v mex_udunits2.c ...
    -I"udunits2-build\include" ...
    -L"udunits2-build\lib" -ludunits2 ...
    -I"expat-build\include" ...
    -L"expat-build\lib" -lexpat

