function S = probeConfig()
S = struct();
S.CDP = struct( ...
    "templateSuffix","QQQ", ...
    "rawSuffix","NRB", ...
    "outRate","CDPrate" );
S.PCASP1 = struct( ...
    "templateSuffix","PC1", ...
    "rawSuffix","OBR", ...
    "outRate","PCASPrate" );
S.PCASP2 = struct( ...
    "templateSuffix","PC2", ...
    "rawSuffix","IBR", ...
    "outRate","PCASPrate" );
end