function XXXX = p1_XXXX(fq,p0,q,ta,tb)
%BLURF
%    XXXX = BLURF(FQ,P0,Q,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    16-May-2026 16:09:47

t2 = ta.^2;
t3 = tb.^2;
t4 = t2+t3+1.0;
XXXX = -(-t4.*(p0+q)+fq.*t2+fq.*t3)./t4;
end