function out1 = fq1_alpha(dpa,dpb,dpra)
%FQ1_ALPHA
%    OUT1 = FQ1_ALPHA(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-May-2026 09:52:34

t2 = dpa.^2;
out1 = dpa+dpra.*2.0-((t2.*2.0+dpb.^2).*(dpa.*dpb+dpb.*dpra.*2.0+sqrt(2.0).*dpb.*sqrt(t2+dpa.*dpra.*2.0+dpra.^2.*2.0)))./(dpb.*t2.*2.0);
end
