function out1 = q1_alpha(dp1a,dpa,dpb,dpra)
%Q1_ALPHA
%    OUT1 = Q1_ALPHA(DP1A,DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-May-2026 09:52:34

t2 = dpa.^2;
out1 = dp1a-((t2+dpb.^2).*(dpa.*dpb+dpb.*dpra.*2.0+sqrt(2.0).*dpb.*sqrt(t2+dpa.*dpra.*2.0+dpra.^2.*2.0)))./(dpb.*t2.*2.0);
end
