function out1 = ta1_alpha(dpa,dpb,dpra)
%TA1_ALPHA
%    OUT1 = TA1_ALPHA(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-May-2026 09:52:34

t2 = dpa.*dpb;
out1 = -(t2+dpb.*dpra.*2.0+sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0))./t2;
end
