function out1 = tb1_alpha(dpa,dpb,dpra)
%TB1_ALPHA
%    OUT1 = TB1_ALPHA(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-May-2026 09:52:34

out1 = -1.0./dpa.^2.*(dpa.*dpb+dpb.*dpra.*2.0+sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0));
end
