function out1 = tb1_beta(dpb,dpr)
%TB1_BETA
%    OUT1 = TB1_BETA(DPB,DPR)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-May-2026 09:52:34

t2 = dpr.*2.0;
out1 = -(dpb+t2+sqrt(2.0).*sqrt(dpb.*t2+dpr.*t2+dpb.^2))./dpb;
end
