function out1 = f_alpha(dp1a,dpa,dpb,dpra)
%F_ALPHA
%    OUT1 = F_ALPHA(DP1A,DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 16:27:31

t2 = dpa.*dpb;
t3 = dpa.^2;
t4 = dpa.^3;
t6 = dpb.^2;
t7 = dpb.^3;
t8 = dpb.^5;
t9 = dpra.^2;
t10 = dpa.*dpra.*2.0;
t11 = dpb.*dpra.*2.0;
t13 = sqrt(2.0);
t12 = t9.*2.0;
t14 = dp1a.*t2.*t3.*4.0;
t15 = dp1a.*dpa.*dpra.*t2.*8.0;
t16 = t3+t10+t12;
t17 = sqrt(t16);
t18 = dpb.*t13.*t17;
t19 = -t18;
t20 = t2+t11+t19;
out1 = (t8-t14-t15+t2.*t4.*6.0+t7.*t9.*1.6e+1-t4.*t20.*2.0+dpb.*t2.^2.*7.0+dp1a.*t3.*t20.*4.0+dp1a.*t6.*t20.*2.0+dpa.*t2.*t9.*1.6e+1-dpb.*t2.*t20.*2.0+dpra.*t2.*t3.*1.6e+1+dpra.*t2.*t6.*1.6e+1-dpra.*t3.*t20.*4.0-dpra.*t6.*t20.*4.0)./(t8+t14+t15+t2.*t4+dpb.*t2.^2.*2.0+dp1a.*dpra.*t7.*8.0+dp1a.*t2.*t6.*4.0-dp1a.^2.*dpa.*t2.*4.0);
end
