function out1 = ta_alpha1(dpa,dpb,dpra)
%TA_ALPHA1
%    OUT1 = TA_ALPHA1(DPA,DPB,DPRA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 16:27:31

t2 = dpa.*dpb;
out1 = -(t2+dpb.*dpra.*2.0-sqrt(2.0).*dpb.*sqrt(dpa.*dpra.*2.0+dpa.^2+dpra.^2.*2.0))./t2;
end
