function out1 = dpr_alpha(fq,ta,tb)
%DPR_ALPHA
%    DPR_ALPHA = DPR_ALPHA(FQ,TA,TB)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    02-Apr-2026 07:40:10

t2 = ta.^2;
out1 = -(-fq+fq.*t2+fq.*ta.*2.0)./(t2.*2.0+tb.^2.*2.0+2.0);
end
